'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

You are the 682124th person to have solved this problem.

'''
import numpy as np

def fib_gen(limit):
    a = 1
    b = 2
    c = a + b
    yield 2
    while c <= limit:
        c = a + b
        print(a, '+', b, '=', c)
        if c %2 == 0:
            print(c)
            yield c
        a = b
        b = c

if __name__ == "__main__":
    max_number = 4000000
    sum = np.sum(fib_gen(max_number))
    print(sum)
